let facebook = {
    infoAbout: "facebook",
    facebook: [
        {
            info: "facebook is an American online,social media and social networking service company based in Menlo park,california en.wikipedia.org",
            headquarters: "Mark zuckberg,Chris Hughes,",
            founders: "Eduardo Severin,Andrew Mc Colon,Dustin Moskovitz",
            founded: "2004",
            employees: "30,275",
        },
    ],

    people: [
        {
            name: "Muhammad azim",
            qualification: "studied industrial and manufacturing",
            wentTo: "NED university of engineering and technology,karachi,pakistan",
            intermediate: "Dj sindh govt.science college",
            school: "Rose house grammer school",
            livesIn: "xian,China",
            from: "karachi,pakistan",
            marriedTo: "someone",
            joined: "january 2019",
        },
        {
            name2: "Tuba mohsin khan",
            qualification: "Software Engineer at NED university",
            college: "studied pre engineering at sent laurence college",
            school: "saint patrick's high school",
            joined: "july 2010",

        },
        {
            name3: "Jee huz",
            qualification: "petrochemical engineering at NED university.karachi,pakistan",
            college: "Govt.Dehli College",
            school: "Islamia public school",
            from: "karachi,Pakistan",
            marriedTo: "no",
        },
        {
            name3: "Zainab salim",
            formerSenior: "software engineer at Recurship",
            formerGeneralSecretary: "At MAPH-Media and Publications house",
            formerWebDesignerAndDeveloper: "At MAPH-Media publications House",
            formerWebAdministrator: "Influx Enterprises",
            studiedAt: "Fast National University Karachi Campus",
            college: "Baharia college at karsaz",
            wentTo: "DHA Model high school phase4",
            livesIn: "karachi,Pakistan",
            from: "Karachi,Pakistan",
            joined: "October 2007",
            followedBy: "750 people",
        },
        {
            name4: "Areeba Aftab",
            studiedAt: "NED University of Engineering and Technology",
            wentTo: "Sunbeams Grammer School",
            livesIn: "Karachi,Pakistan",
            from: "Karachi,Pakistan",
            marriedTo: "Muhammad Arif Ahmed",
        },
        {
            name5: "Muhammad Arif Ahmed",
            systemEngineerAt: "Texpo",
            studiedAt: "Govt.Degree College Gulshan-e-Iqbal",
            wentTo: "Gulistan shah Abdul Latif School(Boys and Girls),karachi",
            livesIn: "Dubai,United Arab Emirates",
            from: "karachi,Pakistan",
            marriedTo: "Areeba Aftab",
        },
        {
            name6: "Saeeda Alam",
            studiedAt: "Islamia College for Women",
            wentTo: "Brazil school,karachi",
        },
        {
            name7: "Esra Mansoor Beyg",
            college: "Khatoon-e-Pakistan",
            school: "Sunbeams Grammer School",
            GoesTo: "Bahria university-karachi",
            livesIn: "Karachi,Pakistan,single",
        },
        {
            name8: "Faisal Merchant",
            worksAt: "Texpo",
            studiedAt: "Preston's college",
            marriedTo: "someone",
        },
        {
            name9: "Md Talha Sheikh",
            worksAt: "Mechanical Maintenance",
            workedAt: "Communication skill",
            studiesAt: "Mechatronics Engineering",
            wentTo: "Aman Tech",
            college: "Govt Dehli College",
            school: "sent laurence",
            livesIn: "karachi",
            joined: "August 2018",
        },
        {
            name10: "Md.Amir",
            studiesAt: "UBIT-computer science department",
            college: "Govt.Degree College",
            wentTo: "Presidential initiative for Artificial Intelligence and computing",
            livesIn: "Karachi,Pakistan",
        },
        {
            name11: "Mahi Ladi",
            worksAt: "student",
            studiedAt: "Punjab group of college",
            wentTo: "Lahore Grammer School",
            livesIn: "Rome,Itly",
            from: "Rome,Itly",
        },
        {
            name12: "Mudassir shams",
            wentTo: "Merit n Merit school",
            college: "Govt Degree college",
            school: "The Grammer School",
            followedBy: "107 peolpe",

        },
        {
            name13: "Ayan Ali",
            workesAt: "photographers worksshops",
            workesAt: "Amateur photographer",
            studiedAt: "University of karachi",
            livesIn: "karachi",
            from: "karachi,Pakistan",
            joined: "November,2014",

        },
        {
            name14: "Md Aqib",
            studiedAt: "University of karachi",
            studiesAt: "Digiskills.pk",
            college: "Govt.college for men",
            studiedAt: "Adamjee coaching centre",
            goesTo: "Tabanis school of Accountancy",
            joined: "August 2013",
            school: "Rehman children secondary school",
            livesIn: "Karachi,Pakistan",
        },
        {
            name15: "Arman khan",
            modelAT: "Modling photography",
            studiedAt: "California college",
            wentTo: "california high school",
            single: "",
        },
        {
            name16: "Abdullah moiz",
            wentTo: "Rose House Grammer School",
            livesIn: "Karachi,Pakistan",
            from: "Orangi",
            joined: "july 2016",
        },
        {
            name16: "saad shah",
            studiedAt: "Govt.Degree Boys college",
            wentTo: "Karachi Grammer School",
            livesIn: "karachi Pakistan",
        },
        {
            name17: "Md.Saqib Ali",
            creativeArtDirector: "At Freelance Graphic Designer",
            directorAt: "The Ambitious Academy Official",
            educationalConsultantAt: "Rose Grammer School",
            studiedAt: "Pakistan shipowner's govt college",
            school: "Rose house grammer school",
            studiedMaArabic: "At university of karachi",
            livesIn: "karachi,Pakistan",
            from: "Orangi Town",
            followedBy: "46 people",

        },
        {
            name18: "Arbaaz sardar",
            studiedAt: "Mak Way Grammer",
            livesIn: "Karachi,Pakistan",
            from: "Karachi,pakistan",
            joined: "october,2014",
            followedBy: "67 people",
        },


        {
            name20: "Abdul Mudassir",
            wentTo: "shaheen public secondary school",
            studiedAt: "Aman tech",
            livesIn: "Karachi,Pakistan",
            from: "Karachi,pakistan",
            engaged: "withsomeone",
            followedBy: "59 people",
        },
        {
            name21: "Mahnoor fatima",
            studiedAt: "NED university of engineering and technology",
            from: "karachi,pakistan",
        },
        {
            name22: "Fauzia Ayub",
            graphicDesignerAt: "technology",
            formerGraphicDesignInternAt: "Far eastern impax(Pvt)ltd",
            studiedPreEngineeringAt: "E complex college",
            wentTo: "Gallant foundation school",
            engagedTo: "Md Noman",
            joinedTo: "2011",
        },
        {
            name23: "Tasweer Rizvi",
            govermentGirlsCollegeAt: "Associate professor of zoology",
            workedAt: "Goverment girls college",
            studiedMscZoologyAt: "university of karachi",
            livesIn: "karachi,pakistan",
            joinedTo: "February 2010",
        },
        {
            name24: "saddam Khan",
            worksAt: "Pakistan navy",
            studiedAt: "peshawar public school and college warsak road peshawar",
            livesIn: "Peshawar,pakistan",
            from: "peshawar,pakistan",
            followedBy: "13 people",
        },
        {
            name25: "Sameen Mughal",
            worksAt: "spectray education centre",
            studiedAt: "goverment degree girls college sector 11-i north karachi",
            livesIn: "karachi,pakistan",
            followedBy: "216 people",
        },
        {
            name26: "Hafsa malik",
            studingAt: "facebook",
            formerStudingAt: "student",
            studiedFscAt: "punjab group of colleges",
            wentTo: "punjab college",
            livesIn: "Lahore,pakistan",
            joinedTo: "february 2018",
            followedBy: "998 people",
        },
        {
            name27: "kashan shah",
            livesIn: "karachi,pakistan",
            followedBy: "280 people",
            joinedTo: "july 2015",
        },
        {
            name28: "Md.zeeshan",
            formerTeacherAt: "Teaching degree link",
            studiedComputerScienceAt: "university of karachi",
            studiedPreEngineering: "Govt college for men",
            livesIn: "Karachi,pakistan",
            from: "orangi town,karachi",
            followedBy: "18people",
        },
        {
            name29: "Tahseen jilani",
            associateProfessorAt: "university of karachi",
            postDoctoralDateScientistAt: "university of karachi",
            studiedComputerSciencephdAt: "uni of karachi",
            studiedAt: "institute of business administration,karachi",
            studiedAt: "applied economics research centre",
        },
        {
            name30: "Fahad haroon",
            wentTo: "university of karachi",
            school: "st.paul's english high school,karachi",
            livesIn: "karachi,pakistan",
            followedBy: "14 people",
        },
        {
            name31: "shahroz asad",
            webApplicationDeveloperAt: "Mayn farmez solutions",
            studiedPreEngineeringAt: "Dj sindh govt.science college",
            studiedCompScience: "uni pf karachi",
            livesIn: "karachi,pakistan",
            from: "karachi,pakistan",
        },
        {
            name32: "Mujahid murshid",
            TeacherAt: "Al-khair commerce coaching",
            studiedAt: "govt.degree college",
            studiedAt: "university of karachi",
            livesIn: "karachi,pakistan",
            from: "orangi",
            joinedTo: "june,2014",
        },
        {
            name33: "Huzaifa hujji",
            workesAt: "Farmer studying at studying",
            goesTo: "The grammer school",
            wentTo: "Engineers and doctors inn",
            from: "karachi,pakistan",
            livesIn: "karachi",
            joinedTo: "september,2015",
        },
        {
            name34: "Afshan jamal",
            directorOfSeaquestLogisticAndTheLawyersAt: "facebook at work",
            studiedAt: "university of karachi",
            wentTo: "karachi grammer school",
            livesIn: "karachi,pakistan",
            followedBy: "235 people",
        },
        {
            name35: "Asad sheikh",
            studiedAt: "Anees hussain excellance in education",
            studiedAt: "govt.college for men nazimabad",
            wentTo: "practical centre",
            school: "sadra english high school",
            livesIn: "karachi,pakistan",
            from: "karachi,pakistan",
            joinedTo: "january 2019",
        },
        {
            name36: "Md Hassan",
            workesAt: "pak navy",
            studiedAt: "govt,college for men,nazimabad",
            wentTo: "Decent english sec school",
            livesIn: "karachi",
            from: "karachi,pakistan",
            joinedTo: "May 2015",
        },
        {
            name37: "sheikh saadi",
            studiedAt: "Govt.National College Bahadurabad",
            wentTo: "islamia english model school",
            livesIn: "karachi,pakistan",
        },
        {
            name37: "sheikh usman",
            financialControllerAt: "AGPR,Karachi",
            studiedAt: "pakistan institute of public finance accountants",
            wentTo: "Makhdoomia sec school",
            livesIn: "karachi",
            from: "karachi",
        },
        {
            name38: "Huzaifa baloch",
            worksAt: "karachi,pakistan",
            studiedAt: "iqra uni",
            livesIn: "Malir cantonment",
            from: "Malir cantonment",
        },
        {
            name39: "Tania Tania",
            worksAt: "facebook",
            wentTo: "karachi grammer school",
            livesIn: "karachi,pakistan",
            from: "karachi,pakistan",
        },
        {
            name40: "Md Arhum",
            studiedAt: "punjab group of colleges",
            wentTo: "lahore grammer school",
            livesIn: "lahore,paris",
        },
        {
            name41: "Aqib raza",
            ownerAt: "Montissori",
            supplyChainManagerAt: "Raya printing",
            workedAt: "Continental print and pack pvt.ltd",
            studiedAt: "summit school,karachi",
            studiedAt: "British Educational Academy and Day Light school system",
            studiedAt: "govt.city college karachi,pakistan",
            livesIn: "karachi,pakistan",
            from: "karachi,pakistan",
        },
        {
            name42: "Bilawal Awan",
            bbaAt: "Iqra uni",
            studiedAt: "uni of karachi",
            wentTo: "superior english school",
            livesIn: "karachi,pakistan",
            engaged: "with someone",
            followedBy: "328",
        },
        {
            name43: "Champ Harry",
            wentTo: "Allied school",
            livesIn: "faisalabad",
            from: "faisalabad",
            followedBy: "856 people",
        },
        {
            name44: "Md Rafique",
            worksAt: "facebook",
            studiedAt: "govt high school jhang city",
            livesIn: "peshawar,paris",
            from: "jhang sardar,punjab,pakistan",
        },
        {
            name45: "Rana waqar",
            projectEngineeringAt: "HVACR",
            studiedAt: "uni of the punjab",
            livesIn: "Al hamidiyan",
            from: "Dubai,united arab emirates",
            joinedTo: "November,2014",
        },
        {
            name46: "shahir alam",
            clerkAt: "Gatron industries limited hub,balochistan",
            studiedAt: "uni of karachi",
            livesIn: "karachi,pakistan",
            from: "karachi,pakistan",
            followedBy: "83 people",
        },
        {
            name47: "Md khalid",
            studiedAt: "FSC at fauji foundation higher sec school",
            livesIn: "Talagang",
            from: "Talagang",
        },
        {
            name48: "Batool zahra",
            adminAt: "karbala stories",
            writerBloggerAT: "swat-social welfare and trust(IOBM socity)",
            workesAt: "Mainbolunga",
            wentTo: "uni of karachi",
            livesIn: "karachi,pakistan",
            from: "karachi,pakistan",
            joinedTo: "june 2017",
        },
        {
            name49: "Bushra Ahmed",
            studiesAt: "NED Uni of engineering and technology",
            studiedAt: "Govt.degree college malir cantt,karachi",
            joinedTo: "August 2011",
        },
        {
            name50: "Komal Ansari",
            studiedAt: "Sir syed uni of Engineering and tech",
            livesIn: "karachi,pakistan",
            from: "karachi,pakiatan",
            joined: "july,2018",
        },
        {
            name51: "Ahad raza mir",
            workesAt: "Dramas central and best pakistani dramas",
            livesIn: "canada,karsaz",
            from: "lahare,pakistan",
            engaged: "withsomeone",
        },
        {
            name52: "Ahad Siddiqui",
            studiedAt: "iqra uni-IU",
            studiedAt: "PECHS",
            livesIn: "karachi,pakistan",
            from: "karachi,pakistan",
        },
        {
            name53: "Imran ali",
            workesAt: "Thai social worker",
            workesAt: "Lords place thai resturent",
            from: "Bankok,Thailand",
            marriedTo: "married",
        },
        {
            name54: "Nawab zyada Ali",
            employ: "self Employed",
            studiedAt: "piston uni karachi",
            wentTo: "Electronics Engineering Department Quest Nawabshah",
            livesIn: "Quetta,Pakistan",
            from: "Nawabshah",
            joined: "february 2014",

        },
        {
            name55: "Muhammad adeel",
            qualification: "studied industrial and manufacturing",
            wentTo: "NED university of engineering and technology,karachi,pakistan",
            intermediate: "Dj sindh govt.science college",
            school: "The smart school",
            livesIn: "Itly",
            from: "karachi,pakistan",
            marriedTo: "someone",
            joined: "juli,2019",
        },
        {
            name56: " Dr.Taskeen",
            qualification: "MBBS",
            wentTo: "DAW Medical uni,karachi,pakistan",
            intermediate: "Govt.degree college for women",
            school: "The smart school",
            livesIn: "Itly",
            from: "karachi,pakistan",
            marriedTo: "someone",
            joined: "juli,2019",
        },
        {
            name57: "Arsala",
            formerSenior: "software engineer at Recurship",
            formerGeneralSecretary: "At MAPH-Media and Publications house",
            formerWebDesignerAndDeveloper: "At MAPH-Media publications House",
            formerWebAdministrator: "Influx Enterprises",
            studiedAt: "Fast National University Karachi Campus",
            college: "Baharia college at karsaz",
            wentTo: "DHA Model high school phase4",
            livesIn: "karachi,Pakistan",
            from: "Karachi,Pakistan",
            joined: "October 2007",
            followedBy: "750 people",
        },
        {
            name58: "Md Jibran",
            studyingAt: "Fazaiya degree college",
            studiesPreEngineeringAt: "fazaiya degree colleg",
            livesIn: "Karachi,pakistan",
            joinedTo: "september 2014",
        },
        {
            name59: "Mudassar haraj",
            worksAt: "karachi",
            studiesAt: "sindh technical board karachi",
            studiedAt: "punjab group of colleges",
            school: "Govt. high school garha more",
            livesIn: "khanewale",
            joinedTo: "july 2018",
        },
        {
            name60: "Tabassum rasheed",
            studiedEngineeringAt: "Bahria college karsaz",
            wentTo: "Bahria Model schools majeed SRE,Karachi",
            livesIn: "karachi,pakistan",
            followedBy: "341 people",

        },
        {
            name61: "Kashan Fareed",
            worksAt: "SOS Hermann gmeiner school",
            workesAt: "Linguaphile Academia",
            studiedAt: "Department of economics uni of karachi",
            studiedAt: "SOS Hermann gmeiner school",
            livesIn: "karachi,pakistan",
            from: "karachi,pakistan",
        },
        {
            name62: "Asfand yar",
            chemistryLecturarAt: "Bahria college karsaz",
            workedAt: "The professor academy",
            studiedDepartmentOfChemistry: "Uni of karachi",
            livesIn: "karachi,pakistan",
            from: "karachi,pakistan",
            joinedTo: "january,2011",
        },
        {
            name63: "Areeba waseem",
            interneeAt: "TCF Alumni development programmer",
            formerStudyingAt: "The professor's academy",
            studiesAt: "IBA-Institute of business administration",
            wentTo: "Mohammadi girls school",
        },
        {
            name64: "Sheraz hakeem",
            studiesMedicineAt: "Agha khan university",
            studiedAt: "McMaster uni",
            wentTo: "Meadowvale secondary school",
            wentTo: "Glenforest see school",
            livesIn: "Mississauga,Ontario",
            joined: "june,2009",
            followedBy: "193 people",
        },
        {
            name65: "Shaheer talha",
            miningEngineeringStudentCoopAt: "Atlantic gold corporation",
            formerFryCookAt: "The Krusty kerab",
            studiedAt: "university of British columbia",
            studiedIbWorldSchoolAt: "The international school",
            wentTo: "The international school",
            livesIn: "Vancouver,British columbia",
            from: "karachi,pakistan",
            joined: "December,2010",
        },
        {
            name66: "Bilal khan",
            studiesAt: "Iqra uni-IU",
            livesIn: "karachi,pakistan",
            from: "karachi,pakistan",
            followedBy: "338 people",
        },
        {
            name67: "Rafina Muneer",
            studiedAt: "Sir syed govt girls college Nazimabad",
            wentTo: "S.M Hafiz -ur-Rehman high school",
            wentTo: "Uni of karachi",
            livesIn: "karachi,pakistan",
            from: "karachi,pakistan",
            joined: "November,2015",
        },
        {
            name68: "Riffat muneer",
            studiedMicrobiologyAt: "jinnah uni for women",
            studiedAt: "Govt college for women",
            school: "S.M Hafiz-ur-Rehman high school",
            livesIn: "karachi,pakistan",
            from: "karachi,pakistan",
            joined: "september,2015",

        },
        {
            name69: "Faisal",
            sailorAt: "Pak navy",
            wentTo: "Nust school of electrical engineering and computer science",
            livesIn: "karsaz,pakistan",
            from: "karachi,pakistan",
            joined: "August,2017",
        },
        {
            name70: "Syed Ali Haider",
            engineerAt: "facebook",
            goesTo: "Bright success college",
            livesIn: "karachi",
            from: "karachi,pakistan",
            followedBy: "27,people",
        },
        {
            name71: "Syed Waqar Abbas",
            worksAt: "Photography",
            studiedAt: "Aisha Bawany College",
            wentTo: "seven seas academy",
            livesIn: "karachi,pakistan",
            from: "karachi,pakistan",
            joined: "August,2017",
        },
        {
            name72: "Usman Ali",
            worksAt: "Pak Army",
            studiedAt: "Punjab group of colleges",
            livesIn: "Mianwali",
            from: "Mianwali kareshian,punjab pakistan",

        },
        {
            name73: "Maham siddiqui",
            formerTeacherAt: "White house grammer school",
            formerEnglishCopyWriterAt: "ABB Takk",
            formerInterneeAt: "Radio pakistan news",
            studiedGraduationAt: "Sir syed government girls college",
            wentTo: "karachi Grammer School",
            livesIn: "Karachi,pakistan",
            from: "karachi,pakistan",
            followedBy: "1,175 people",
        },
        {
            name74: "Manzi Naqvi",
            studiedAt: "National textile uni(NTU)",
            studiedAt: "New Fazaiya intermedite college Base Faisal karachi",
            wentTo: "Howard grammer school",
            livesIn: "karachi,pakistan",
            from: "karachi,Pakistan",
            followedBy: "284 people",
        },
        {
            name75: "Shuja Abbas",
            studiedMechanicalEngineer: "Radha Govind Engg-College,Mearut",
            studiedAt: "Shri,Ram public inter,college",
            livesIn: "New Dehli",
            from: "Amroha",
            followedBy: "327 people",
        },
        {
            name76: "Tabinda jamal",
            studiedAt: "Usmania uni",
            wentTo: "Dawn high school",
            livesIn: "Hydrabad",
            from: "New Dehli,india",
        },
        {
            name77: "Usama Ch",
            worksAt: "Designer social",
            studiedAt: "Punjab group of colleges",
            wentTo: "City public school",
            livesIn: "Sialkot,punjab",
            from: "Sialkot,punjab",

        },
        {
            name78: "Meshi khan",
            worksAt: "Student",
            studiedAt: "Punjab group of colleges",
            wentTo: "Lahore grammer school",
            livesIn: "lahore,pakistan",
            from: "Lahore",
        },
        {
            name79: "Ayesha khan",
            studiedAt: "Punjab group of colleges",
            wentTo: "Karachi,pakistan",
            from: "karachi,pakistan",
        },
        {
            name80: "Iqra khan",
            studiedAt: "Punjab college",
            wentTo: "Lahore grammer school",
            livesIn: "lahore,pakistan",
            from: "lahore,pakistan",
        },
        {
            name81: "Hashmi",
            lieutmentAt: "Son of land,pak army",
            studiedAt: "Cadet college rawalpindi",
            wentTo: "Karachi public school",
            livesIn: "karachi,pakistan",
            followedBy: "255 people",
        },
        {
            name82: "Kanza khan",
            studiedAt: "KG F6/2 islamabad",
            livesIn: "Islamabad,pakistan",
            followedBy: "585 people",
        },
        {
            name83: "Sabir Ali",
            studiedAt: "Lyari general hospital,karachi",
            studiedAt: "Daw uni of health science",
            goesTo: "Muslim primary And sec school",
            livesIn: "Karachi,pakistan",
            from: "karachi,pakistan",
        },
        {
            name84:"Sulman khalid",
            studiedAt:"Pir Mehr Ali Shah Arid Agricultural uni",
            studiedAt:"Asghar Mall College",
            wentTo:"Sir syed public secondary",
            livesIn:"Rawalpindi",
            from:"Rawalpindi",
            joined:"july,2014",
        },
        {
            name85:"Shariq Iqbal",
            OwnBusinessAt:"CEX logistics",
            studiesAt:"uni of karachi",
            studiedAt:"PECHS Education Foundation Government Science College",
            studiedAt:"Oxford high school,karachi",
            livesIn:"karachi,pakistan",
            from:"karachi,pakistan",
            joined:"April,2012",
            followedBy:"362 people",
        },
        {
            name86:"Sheharyar khan",
            worksAt:"Makhdoomia sec school",
            studiedAt:"Govt.premier college karachiNo1",
            livesIn:"karachi,pakistan",
            from:"karachi,pakistan",
        },
        {
            name87:"Bilal khan",
            generalSecretaryAt:"karachi,welfare association",
            managingDirectorAt:"Newton's inn coaching centre",
            workesAt:"parliment professional forum at youth parliment",
            scoutMemberAt:"Sindh Boy Scouts Association",
            memberShipDirectorAt:"All sindh private school association",
            formerOwnerOperatorAt:"Iqra academy jannat-ul-atfal",
            studiedAt:"uni of karachi",
            college:"S.M Law govt.college",
            livesIn:"karachi,pakistan",
            from:"karachi,pakistan",
            joined:"November,2011",
            followedBy:"849 people",

        },
        {
            name88:"Zawar saif ali jee",
            karachiAt:"comp science engineering's students ashoka institute",
            studiesAt:"Cannt college science and commerce",
            studiedAt:"uni of karachi",
            wentTo:"Well-Done cambridge school",
            livesIn:"karachi,pakistan",
            from:"karachi,pakistan",
            joined:"july,2014",
        },
        {
            name89:"Abdul Rafae khan",
            formerStudentsAt:"Pak army",
            studiedAt:"Govt.Monotechnic institute malir,karachi",
            studiesAt:"Govt.jamia millia",
            wentTo:"The Smart School-Tss",
            livesIn:"karachi,pakistan",
            from:"Malir",
        },
        {
            name90:"Nintytwo",
            worksAt:"92 productrion",
            studiedAt:"intermediat private",
            wentTo:"Khan Liaquat Ali Khan High School",
            livesIn:"karachi,pakistan",
            from:"karachi,pakistan",
        },
        {
            name91:"Ammar khan",
            worksAt:"Showbiz pakistan",
            salesPromotionsRepresentativeAt:"OPPO",
            studiesBscsAt:"indus uni",
            studiedAt:"DAE Diploma of association engineering",
            wentTo:"The City School",
            livesIn:"Karachi,pakistan",
            followedBy:"956,people",
        },
        {
            name92:"Zeba waqar",
            salesReprentativeAt:"House Tag",
            studiedAt:"Official iqra uni",
            wentTo:"St Andreu's high school",
            livesIn:"karachi,pakistan",
            from:"karachi,pakistan",
        },
        {
            name93:"Zoni kanwal",
            studiedAt:"Uni of sargodha",
            wentTo:"City school sodhra",
            from:"Gujranwala,pakistan",
        },
        {
            name94:"Tariq Rasool",
            studyingAt:"studying",
            studiedAt:"Punjab group of college",
            wentTo:"Govt.model high school jampur",
            livesIn:"Dera ghazi khan",
            from:"Multan",

        },
        {
            name95:"Musaib shah",
            chefAt:"Govt.superior science colleges",
            wentTo:"New Rawalpindi",
            livesIn:"korangi,sindh",
            from:"korangi,colony,sindh,pakistan",
            joined:"August,2017",
        },
        {
            name96:"Arhaan khan",
            worksAt:"Actor model",
            studiedAt:"uni of lahore",
            livesIn:"karachi,pakistan",
            from:"Islamabad,pakistan",
            joined:"March,2017",
            followedBy:"1,755 people",
        },
        {
            name97:"Shah zaib khan",
            tourManagerAt:"Kashi",
            studiedFriendshipAt:"Govt.degree malir cannt college",
            studiedAt:"SOS Hermann Gemeiner Higher Sec Sch",
            wentTo:"SOS Hermann Gmeiner Higher Sec.Sch",
            livesIn:"karachi,pakistan",
            from:"karachi,pakistan",
        },
        {
            name98:"Shoib Akhter",
            studiedAt:"Army public school and college Bahawalpur Cantt",
            livesIn:"Karachi,pakistan",
            from:"Bahawalpur",
            joined:"Feb,2014",
        },
        {
            name99:"Syed Ali Raza",
            worksAt:"Software Engineer",
            livesIn:"Dubai,united arab emirates",
            from:"Dubai,Makkah,saudi arabia",
            followedBy:"623,people",
        },
        {
            name100:"Adeel shahab",
            worksAt:"i am karachi app",
            modelCampsAt:"The professor's academy(T.P.A)",
            studiesAt:"ICMA Pakistan",
            studiedAt:"P.E.C.H.S Education Foundation Govt.Degree science college",
            wentTo:"Seven seas academy",
        },
        {
            name101:"Tanzila wafa",
            worksAt:"Peshawar,pakistan",
            studiedAt:"Uni of Peshawar",
            wentTo:"Uni of peshawar",
            livesIn:"Peshawar,pakistan",
            from:"Hayatabad",
        },
        {
            name102:"Asvins life",
            directorAt:"Chandigarh,india",
            from:"Chandigarh,india",
        },
        {
            name103:"Rahul healthcare",
            worksAt:"Business",
            studiedAt:"Punjab uni,chandigarh",
            livesIn:"Yamunanagr",
            from:"Bilaspur,haryana,india",
        },
        {
            name104:"Dr.Shayan sst",
            goesTo:"navi mumbai high school",
            livesIn:"navi mumbai high school",
            from:"Mumbai",
        },
        {
            name105:"Shahzaib khan",
            tourManagerAt:"kashi",
            studiedFriendshipAt:"Govt.degree malir cantt college",
            studiesAt:"SOS Hermann Gemeiner Higher Sec.School",
            wentTo:"SOS Hermann gmeiner school",
            livesIn:"karachi,pakistan",
            from:"karachi,pakistan",
        },
        {
            name106:"Wajih Alam",
            managerAt:"Think wide spark tutors",
            workesAt:"Academy of spark",
            salesConsultantAt:"EFU lives Assurance,LTD",
            volunteerAt:"Improving Humanity",
            memberShipHeadAt:"spark ignity lives",
            studiedSoftwareEngineerAt:"Hamdard uni",
            studiesPreEngineeringAt:"D.j sindh govt sci college",
            wentTo:"The children academy",
            livesIn:"karachi,pakistan",
        },
        {
            name107:"Akhter Hussain",
            studiedAt:"Punjab uni lahore pakistan/preston uni islamabad",
            studiedAt:"Govt.computer training institute",
            wentTo:"Govt.C.D islamia high school talwandi bhindra narowal",
            livesIn:"islamabad,pakistan",
            from:"Narowal",
        },
        {
            name108:"Azeem Shiekh",
            formerIntershipAt:"Facebook",
            studiedAt:"uni of karachi",
            wentTo:"The city school official",
            livesIn:"karachi,pakistan",
            from:"karachi,pakistan",
            followedBy:"67,people",
        },
        {
            name109:"Arhama",
            modelAt:"Eviolution Telent Management",
            formerVolunteerAt:"Darul sulman",
            formerVolunteerAt:"Idara Al-khair",
            studiesAt:"Bahria uni karsaz camp",
            livesIn:"karachi,pakistan",
            from:"karachi,pakistan",
        },
        {
            name110:"Aleem",
            formerAccountantAt:"Tecnia Gmbh",
            studiedAt:"LN Gupta science and commerce college",
            studiedAccountancyAt:"Govt.junior college aliya gunfoundry hydrabad",
            wentTo:"Golconda high school",
            livesIn:"Hydrabad",
            from:"Hydrabad",
            joined:"june,2014",
        },
        {
            name111:"Ashar ali sheikh",
            mbbsAt:"studying",
            studiesAt:"Jinnah sindh medical uni",
            livesIn:"karachi,pakistan",
        },
        {
            name112:"Taha Ali khan",
            formerDesignerAt:"Fabricon",
            studiedAt:"uni of karachi",
            wentTo:"The Fahim School",
            followedBy:"164 people",
        },
        {
            name113:"Yawar Taqvi",
            cashierAt:"Bank Al Habib Limited",
            studiedAt:"Pak shipowner's govt college",
            studiedAt:"Faderal urdu uni of Arts,science and technology",
            wentTo:"Mighty minds academy",
            livesIn:"karachi,pakistan",
            joined:"july,2011",
        },
        {
            name114:"Hasham Khokhar",
            businessOwnerAt:"Rayans Maruee",
            softEngineerAt:"facebook",
            formerStudyingAt:"studying",
            studiedAt:"indus college of sci and commerce islamabad",
            wentTo:"Chanab group of college telangang",
            livesIn:"Islamabad,pakistan",
            from:"Islamabad,pakistan",
        },
        {
            name115:"Kamran khan",
            cricket:"All rounder",
            workesAt:"facebook",
            wentTo:"Shaheer Model High School",
            livesIn:"Yar hussain khyber,pakistan",
            from:"Yar hussain khyber,pakistan",
            joined:"Dec,2017"
        },
        {
            name116:"Md.Haris Mushtaque",
            worksAt:"SMBB Trauma centre civil hospital karachi",
            administrativeOfficerAt:"child life foundation",
            studiedAt:"Department of public administration uni of karachi",
            wentTo:"Jinnah public school",
            livesIn:"karachi,pakistan",
            from:"karachi,pakistan",
        },
        {
            name117:"Syed Akif",
            mathsTeacherMainCampusAt:"Adamjee coaching centre",
            formerPhisicsInstructorAt:"Shah collegiate",
            studiedAt:"chemical engineer,uni of karachi",
            studiedPreEngineeringAt:"Govt.dehli college",
            studiedAt:"Practical centre",
            goesTo:"Rahman children sec school",
            joined:"April,2015",
        },
        {
            name118:"Abdul Malik",
            stopNurseAt:"civil hospital karachi",
            worksAt:"civil hospital,karachi DOW uni of health sciences",
            studiedAt:"pakistan,pharmacist",
            wentTo:"Allied school heroon bahria karachi",
            livesIn:"karachi,pakistan",
            joined:"june,2017",
        },
        {
            name119:"Mujeeb Rao",
            studiesAt:"Uni of karachi",
            wentTo:"Govt.Abbasia higher school",
            wentTo:"Govt.Abbasia Higher School",
            livesIn:"karachi,pakistan",
            from:"Bahawalpur",
            joined:"july,2017",

        },
        {
            name120:"Md.Haris Mushtaqe",
            worksAt:"SMBB Trauma centre civil hospital karachi",
            administrativeOfficerAt:"child life foundation",
            studiedAt:"Department of public administration",
            wentTo:"Jinnah public school",
            livesIn:"karachi,pakistan",
            from:"karachi,pakistan",
        },
        {
            name121:"Akram salvi",
            livesIn:"kuala lampur malaysia",
            from:"Mailsi,punjab,pakistan",
            followedBy:"263,people",
        },
        {
            name122:"Md.Ammar",
            studiedZoologyAt:"G.C uni faisalabad",
            studiedAt:"G.C college jhang",
            wentTo:"G.C College",
            school:"Govt.higher sec school bagh jhang",
            livesIn:"Punjab,pakistan",
            from:"Punjab,pakistan",
            joined:"Oct,2014",
            followedBy:"109 people",
        },
        {
            name123:"Javeria Ali",
            studiedElecEngiAt:"NED Uni",
            studiedAt:"Khatoon-e-pakistan",
            wentTo:"The City Kehlakashla school",
        },
        {
            name124:"Sharmeen wajia",
            studiedAt:"NED Uni of Engineering and Technolgy",
            wentTo:"BAMM PECHS Govt.college for Women",
            wentTo:"The Educators jauhar campus-official",
            livesIn:"karachi,pakistan",
            from:"karachi,pakistan",
            joined:"july,2012",
        },
        {
            name125:"Wajiha Sharmeen",
            studiedAt:"BAMM P.E.C.H.S GIRLS College",
            goesTo:"karachi,pakistan",
            wentTo:"Rose House Grammer School",
            livesIn:"karachi,pakistan",
        },
        {
            name126:"Samra Saeed",
            worksAt:"Studying Law",
            wentTo:"Mustafvi Model school/college",
            livesIn:"Lahore,pakistan",
            from:"Sialkot,punjab",
        },
        {
            name127:"Kokab Shaqil",
            scienceTeacherAt:"Baharia foundation college johar camp",
            formerScienceTeacherAt:"Azeem school ACPS",
            formerTeacherAt:"ST lawrence gram school blockW,",
            studiedAt:"Govt.college for women nazimabad,karachi",
            studiedAt:"karachi,pakistan",
            wentTo:"Rose house grammer school",
            livesIn:"karachi,pakistan",
            from:"Orangi",
        },
        {
            name128:"Kawkab shaqil",
            studiesElectricEngiAt:"institute of business management",
            studiedEconomicsAndManagementAt:"uni of putra",
            livesIn:"karachi,pakistan",
            from:"Dawha at qatar",
            joined:"April,2010",
        },
        {
            name129:"Shahla Maryam",
            makeUpArtistAt:"style 360TV",
            studiedAt:"Punjab group of colleges",
            wentTo:"Sadiq public school rawalpindi",
            livesIn:"Rawalpindi,pakistan",
            from:"Rawalpindi,pakistan",
        },
        {
            name130:"Hasna Aksar",
            worksAt:"Oriflame",
            studiedAt:"Khairiya muslim girls college",
            wentTo:"Khairiya Muslim",
            livesIn:"Colombo,srilanka",
            from:"colombo,srilanka",
            engaged:"with some",
            joined:"feb,2018",
        },
        {
            name131:"Joy Bakers",
            studiedAt:"ilma inter girls school",
            wentTo:"ILMA international",
            livesIn:"Dehiwela,srilanka",
            from:"Colombo,srilanka",
            followedBy:"23 people",
        },
        {
            name132:"Umer shaqil",
            teamleadAt:"ibex.connect",
            formerSeniorNetworkEngineerAt:"Ibex Global",
            formerNocNetEngineerAt:"Ibex global TRG",
            formerSeniorNetworkEngineerAt:"Artistic garment industries and artists",
            formerNetworkEngiAt:"Systellex",
            wentTo:"Hamdard public school",
            livesIn:"karachi,pakistan",
            from:"karachi,pakistan",
        },
        {
            name133:"Atif siddiqui",
            worksAt:"TDPA-Ministry of commerce govt of pakistan",
            studiedAt:"Skill development council karachi",
            studiedAt:"Royal institute of sci and tech",
            studiesAt:"Allama iqbal open uni official",
            studiesAt:"Govt.degree boys college 5-l north,karachi",
            wentTo:"KIDS Paradise academy school",
            wentTo:"little folks paradise sec school 5M north,karachi",
            livesIn:"karachi,pakistan",
            from:"karachi,pakistan",
        },
        {
            name134:"Atif UZ Zaman",
            studyingAt:"P.T.C.P.A Training centre,karachi",
            teamCoordinatorAt:"standard studio",
            teamLeaderAt:"Atif zaman photography",
            photographyStudentAt:"Memon industries and technical institute",
            livesIn:"karachi,pakistan",
            from:"karachi,pakistan",
            followedBy:"489 people",
        },
        {
            name135:"Mehwish jalil",
            internationalBroadCasterAt:"voice of America",
            studiedAt:"uni of peshawar",
            livesIn:"Washington,district of collumbia",
            from:"Peshawar,pakistan",
            joined:"jan,2016",
            followedBy:"4,823",
        },
        {
            name136:"Ramsha khan",
            studiedBiomedicalEngiAt:"NED uni of Engi and technology",
            wentTo:"BAMM PECHS Girls college",
            livesIn:"karachi,pakistan",
            from:"karachi,pakistan",
        },
    ],
}
